### ISSUE TITLE
Some problems with esp32s2tft_simpletest.py

### ISSUE THREAD

**Issue by MadGeometer** [adafruit/Adafruit_CircuitPython_ESP32S2TFT#3] opened 2022-04-03 05:24 UTC
Hello,

Am having some problems with [esp32s2tft_simpletest.py](https://github.com/adafruit/Adafruit_CircuitPython_ESP32S2TFT/blob/main/examples/esp32s2tft_simpletest.py)

1. Why is adafruit_portalbase required? There are other unexpected dependencies as well
2. Nothing is displayed on the TFT!

Any help would be greatly appreciated!
Thanks - Mike

**Comment by FoamyGuy** [comment] 2022-04-03 14:29
@MadGeometer PortalBase is required because the ESP32S2TFT Class extends PortalBase: https://github.com/adafruit/Adafruit_CircuitPython_ESP32S2TFT/blob/760411be59d98b0ab92f770be8938204b0505880/adafruit_esp32s2tft/__init__.py#L46

This library is a helper library that provides high level functions to use without having to micromanage the details. Things like `add_text()` to show some text rather than having to create your own Label object, configure it's properties and then add it to a Group and show it on the display.

**Comment by FoamyGuy** [comment] 2022-04-03 15:57
I tested this out on my Feather TFT and it does appear to display and work properly with the button and neopixel. 

Make sure that you have all of the required libraries installed and it should be working I believe.

If you are comfortable with command line utilities there is a tool called `circup` you can install and then run a command like:
```
circup install -a
```
to automatically install all libraries required by code.py.

**Comment by MadGeometer** [comment] 2022-04-04 01:24
Hi FoamyGuy,

Thanks for telling me about CirCup - none of the libraries required updating. Nothing has changed vis-a-vis the TFT screen. Any other suggestions?

Thanks -- Mike

**Comment by FoamyGuy** [comment] 2022-04-04 01:40
Try to connect to the serial console of your device. If you are using Mu there is a button in there for accessing it. 

Once you're in the serial console send it ctrl-C and then ctrl-D to restart the program and watch for any error messages to get output. It's possible there is some other exception being raised that could prevent it drawing anything. If so this should give you the traceback from it to track down the cause.

**Comment by FoamyGuy** [comment] 2022-04-18 16:26
A few other people ended up reporting similar issues and there was a fix put in to the core discussed here: https://github.com/adafruit/circuitpython/issues/6264

There seems to be some obscure bug that can cause the display not to work. It was resolved on newer versions of circuitpython. If you are still having issues please try updating to at least 7.3.0beta.1

Closing this for now.

**Closed by FoamyGuy** 2022-04-18 16:26 UTC

**Comment by MadGeometer** [comment] 2022-04-30 03:47
CircuitPython 7.3.0-beta.2 works great, thanks!
